
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ci1322.compiler;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 4;
  public static final int RIGHTBRACKET = 12;
  public static final int LEFTSQ = 16;
  public static final int LEFTPAR = 9;
  public static final int N_VAR = 18;
  public static final int RETURN = 6;
  public static final int EOS = 14;
  public static final int FUNCTION = 3;
  public static final int RIGHTPAR = 10;
  public static final int NUM = 19;
  public static final int EQUALS = 8;
  public static final int COMMA = 7;
  public static final int RIGHTSQ = 17;
  public static final int EOF = 0;
  public static final int LESS_THAN = 15;
  public static final int LEFTBRACKET = 11;
  public static final int PRINT = 20;
  public static final int error = 1;
  public static final int INT_TYPE = 13;
  public static final int FOR = 2;
  public static final int ARRAY = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FOR",
  "FUNCTION",
  "READ",
  "ARRAY",
  "RETURN",
  "COMMA",
  "EQUALS",
  "LEFTPAR",
  "RIGHTPAR",
  "LEFTBRACKET",
  "RIGHTBRACKET",
  "INT_TYPE",
  "EOS",
  "LESS_THAN",
  "LEFTSQ",
  "RIGHTSQ",
  "N_VAR",
  "NUM",
  "PRINT"
  };
}

